version: 0.2

phases:
  pre_build:
   commands:
     - echo Logging in to Amazon ECR...
     - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 637994078207.dkr.ecr.ap-south-1.amazonaws.com
     - chmod +x ./Func1/build.sh
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd Func1 ; ./build.sh
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 637994078207.dkr.ecr.ap-south-1.amazonaws.com/ecr-repo-stack-func1ecrrepo38a9a079-xg6kwj8qgtwj:latest