version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install python3-pip -y
      - python3 -m pip install pytest
  pre_build:
   commands:
     - echo Running tests
     - python3 -m pytest ./tests/
     - chmod +x ./Func1/build.sh
     - chmod +x ./Func2/build.sh
  build:
    commands:
      - echo Build started on `date`
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 637994078207.dkr.ecr.ap-south-1.amazonaws.com
      - echo Building the Docker image...
      - cd Func1 ; ./build.sh $func1ECRRepo_URI ; cd ..
      - cd Func2 ; ./build.sh $func2ECRRepo_URI ; cd ..
  post_build:
    commands:
      - echo Build completed on `date`